spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    password: root123
    username: postgres
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: 8080
